[common]
lib_deps =
    https://github.com/lvgl/lvgl.git#v8.4.0
    https://github.com/DCC-EX/DCCEXProtocol.git#v1.4.0-Prod

[env:esp32s3_120_16_8-qio_opi]
platform = espressif32
board = esp32s3_120_16_8-qio_opi
framework = arduino

monitor_speed = 115200

build_flags =
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_VIEWE_UEDX48480021_MD80ET
    -DDEVICE_VIEWE_ROUND
    -DLVGL_PORT_ROTATION_DEGREE=180

lib_deps =
    ${common.lib_deps}
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
    https://github.com/esp-arduino-libs/ESP32_Button.git
    https://github.com/esp-arduino-libs/ESP32_Knob.git
